version: '3.9'

services:

  mongo:
    image: mongo:latest
    hostname: mongo
    container_name: mongo
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    networks:
      - mongo_net

  application:
    image: andriikopytsia/akopytsia
    #build: ../application
    container_name: application
    restart: always
    depends_on:
      - mongo
    ports:
      - 8000:5000
    networks:
      - mongo_net

networks:
  mongo_net:
    driver: bridge
